# Generated by Django 5.0 on 2024-06-11 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_bank_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accountholder',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='deleted_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.PositiveBigIntegerField(error_messages={'unique': 'account number is already exist'}, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Saving', 'Saving'), ('Current', 'Current'), ('Joint', 'Joint')], error_messages={'ACCOUNT_TYPES': 'Select correct Given Account_type'}, max_length=30),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_id',
            field=models.CharField(error_messages={'unique': 'Given bank_id is already used.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_bank_id', message='Bank ID must contain both characters and numbers.', regex='^(?=.*[a-zA-Z])(?=.*\\d)[a-zA-Z\\d]*$')]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(error_messages={'unique': 'Given Branch Id is already used.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_bank_id', message='Bank ID must contain both characters and numbers.', regex='^(?=.*[a-zA-Z])(?=.*\\d)[a-zA-Z\\d]*$')]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Given Email ID is already used in Branch'}, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.PositiveBigIntegerField(error_messages={'unique': 'Given Phone number is already used in Branch'}, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Credit', 'Credit')], error_messages={'Choice': 'Please Select Correct Given Choice'}, max_length=20),
        ),
    ]
